package com.example.demo.pojo;

import java.util.Date;

public class TAccountFlow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_flow.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_flow.account_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_flow.amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_flow.flow_type
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Integer flowType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_flow.available_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Long availableAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_flow.freeze_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Long freezeAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_flow.remark
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_flow.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_flow.id
     *
     * @return the value of t_account_flow.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_flow.id
     *
     * @param id the value for t_account_flow.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_flow.account_id
     *
     * @return the value of t_account_flow.account_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_flow.account_id
     *
     * @param accountId the value for t_account_flow.account_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_flow.amount
     *
     * @return the value of t_account_flow.amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_flow.amount
     *
     * @param amount the value for t_account_flow.amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_flow.flow_type
     *
     * @return the value of t_account_flow.flow_type
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Integer getFlowType() {
        return flowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_flow.flow_type
     *
     * @param flowType the value for t_account_flow.flow_type
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setFlowType(Integer flowType) {
        this.flowType = flowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_flow.available_amount
     *
     * @return the value of t_account_flow.available_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Long getAvailableAmount() {
        return availableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_flow.available_amount
     *
     * @param availableAmount the value for t_account_flow.available_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setAvailableAmount(Long availableAmount) {
        this.availableAmount = availableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_flow.freeze_amount
     *
     * @return the value of t_account_flow.freeze_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Long getFreezeAmount() {
        return freezeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_flow.freeze_amount
     *
     * @param freezeAmount the value for t_account_flow.freeze_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setFreezeAmount(Long freezeAmount) {
        this.freezeAmount = freezeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_flow.remark
     *
     * @return the value of t_account_flow.remark
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_flow.remark
     *
     * @param remark the value for t_account_flow.remark
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_flow.create_time
     *
     * @return the value of t_account_flow.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_flow.create_time
     *
     * @param createTime the value for t_account_flow.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}