package com.example.demo.pojo;

import java.util.Date;

public class TBankCard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bank_card.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bank_card.user_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bank_card.realname
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bank_card.bank_name
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bank_card.card_number
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String cardNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bank_card.branch_name
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String branchName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bank_card.balance
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Long balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bank_card.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bank_card.id
     *
     * @return the value of t_bank_card.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bank_card.id
     *
     * @param id the value for t_bank_card.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bank_card.user_id
     *
     * @return the value of t_bank_card.user_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bank_card.user_id
     *
     * @param userId the value for t_bank_card.user_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bank_card.realname
     *
     * @return the value of t_bank_card.realname
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bank_card.realname
     *
     * @param realname the value for t_bank_card.realname
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bank_card.bank_name
     *
     * @return the value of t_bank_card.bank_name
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bank_card.bank_name
     *
     * @param bankName the value for t_bank_card.bank_name
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bank_card.card_number
     *
     * @return the value of t_bank_card.card_number
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bank_card.card_number
     *
     * @param cardNumber the value for t_bank_card.card_number
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber == null ? null : cardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bank_card.branch_name
     *
     * @return the value of t_bank_card.branch_name
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getBranchName() {
        return branchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bank_card.branch_name
     *
     * @param branchName the value for t_bank_card.branch_name
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setBranchName(String branchName) {
        this.branchName = branchName == null ? null : branchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bank_card.balance
     *
     * @return the value of t_bank_card.balance
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Long getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bank_card.balance
     *
     * @param balance the value for t_bank_card.balance
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setBalance(Long balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bank_card.create_time
     *
     * @return the value of t_bank_card.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bank_card.create_time
     *
     * @param createTime the value for t_bank_card.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}