package com.example.demo.pojo;

import java.util.Date;

public class TBid {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bid.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bid.borrow_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String borrowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bid.borrow_title
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String borrowTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bid.bid_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Long bidAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bid.bid_interest
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Long bidInterest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bid.year_rate
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Integer yearRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bid.borrow_state
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Integer borrowState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bid.bid_user_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String bidUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bid.bid_username
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String bidUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bid.bid_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Date bidTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bid.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bid.id
     *
     * @return the value of t_bid.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bid.id
     *
     * @param id the value for t_bid.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bid.borrow_id
     *
     * @return the value of t_bid.borrow_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getBorrowId() {
        return borrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bid.borrow_id
     *
     * @param borrowId the value for t_bid.borrow_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setBorrowId(String borrowId) {
        this.borrowId = borrowId == null ? null : borrowId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bid.borrow_title
     *
     * @return the value of t_bid.borrow_title
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getBorrowTitle() {
        return borrowTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bid.borrow_title
     *
     * @param borrowTitle the value for t_bid.borrow_title
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setBorrowTitle(String borrowTitle) {
        this.borrowTitle = borrowTitle == null ? null : borrowTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bid.bid_amount
     *
     * @return the value of t_bid.bid_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Long getBidAmount() {
        return bidAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bid.bid_amount
     *
     * @param bidAmount the value for t_bid.bid_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setBidAmount(Long bidAmount) {
        this.bidAmount = bidAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bid.bid_interest
     *
     * @return the value of t_bid.bid_interest
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Long getBidInterest() {
        return bidInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bid.bid_interest
     *
     * @param bidInterest the value for t_bid.bid_interest
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setBidInterest(Long bidInterest) {
        this.bidInterest = bidInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bid.year_rate
     *
     * @return the value of t_bid.year_rate
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Integer getYearRate() {
        return yearRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bid.year_rate
     *
     * @param yearRate the value for t_bid.year_rate
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setYearRate(Integer yearRate) {
        this.yearRate = yearRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bid.borrow_state
     *
     * @return the value of t_bid.borrow_state
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Integer getBorrowState() {
        return borrowState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bid.borrow_state
     *
     * @param borrowState the value for t_bid.borrow_state
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setBorrowState(Integer borrowState) {
        this.borrowState = borrowState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bid.bid_user_id
     *
     * @return the value of t_bid.bid_user_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getBidUserId() {
        return bidUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bid.bid_user_id
     *
     * @param bidUserId the value for t_bid.bid_user_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setBidUserId(String bidUserId) {
        this.bidUserId = bidUserId == null ? null : bidUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bid.bid_username
     *
     * @return the value of t_bid.bid_username
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getBidUsername() {
        return bidUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bid.bid_username
     *
     * @param bidUsername the value for t_bid.bid_username
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setBidUsername(String bidUsername) {
        this.bidUsername = bidUsername == null ? null : bidUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bid.bid_time
     *
     * @return the value of t_bid.bid_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Date getBidTime() {
        return bidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bid.bid_time
     *
     * @param bidTime the value for t_bid.bid_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setBidTime(Date bidTime) {
        this.bidTime = bidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bid.create_time
     *
     * @return the value of t_bid.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bid.create_time
     *
     * @param createTime the value for t_bid.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}