package com.example.demo.pojo;

import java.util.Date;

public class TLoginLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.ip
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.login_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Date loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.username
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.account_type
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Integer accountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.login_result
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Integer loginResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.id
     *
     * @return the value of t_login_log.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.id
     *
     * @param id the value for t_login_log.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.ip
     *
     * @return the value of t_login_log.ip
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.ip
     *
     * @param ip the value for t_login_log.ip
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.login_time
     *
     * @return the value of t_login_log.login_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.login_time
     *
     * @param loginTime the value for t_login_log.login_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.username
     *
     * @return the value of t_login_log.username
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.username
     *
     * @param username the value for t_login_log.username
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.account_type
     *
     * @return the value of t_login_log.account_type
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Integer getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.account_type
     *
     * @param accountType the value for t_login_log.account_type
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setAccountType(Integer accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.login_result
     *
     * @return the value of t_login_log.login_result
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Integer getLoginResult() {
        return loginResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.login_result
     *
     * @param loginResult the value for t_login_log.login_result
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setLoginResult(Integer loginResult) {
        this.loginResult = loginResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.create_time
     *
     * @return the value of t_login_log.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.create_time
     *
     * @param createTime the value for t_login_log.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}