package com.example.demo.pojo;

import java.util.Date;

public class TRecharge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge.user_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge.username
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge.bank_card_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String bankCardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge.trade_no
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String tradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge.amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge.recharge_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Date rechargeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge.state
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge.remark
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recharge.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge.id
     *
     * @return the value of t_recharge.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge.id
     *
     * @param id the value for t_recharge.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge.user_id
     *
     * @return the value of t_recharge.user_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge.user_id
     *
     * @param userId the value for t_recharge.user_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge.username
     *
     * @return the value of t_recharge.username
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge.username
     *
     * @param username the value for t_recharge.username
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge.bank_card_id
     *
     * @return the value of t_recharge.bank_card_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getBankCardId() {
        return bankCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge.bank_card_id
     *
     * @param bankCardId the value for t_recharge.bank_card_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setBankCardId(String bankCardId) {
        this.bankCardId = bankCardId == null ? null : bankCardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge.trade_no
     *
     * @return the value of t_recharge.trade_no
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge.trade_no
     *
     * @param tradeNo the value for t_recharge.trade_no
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge.amount
     *
     * @return the value of t_recharge.amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge.amount
     *
     * @param amount the value for t_recharge.amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge.recharge_time
     *
     * @return the value of t_recharge.recharge_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Date getRechargeTime() {
        return rechargeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge.recharge_time
     *
     * @param rechargeTime the value for t_recharge.recharge_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setRechargeTime(Date rechargeTime) {
        this.rechargeTime = rechargeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge.state
     *
     * @return the value of t_recharge.state
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge.state
     *
     * @param state the value for t_recharge.state
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge.remark
     *
     * @return the value of t_recharge.remark
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge.remark
     *
     * @param remark the value for t_recharge.remark
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recharge.create_time
     *
     * @return the value of t_recharge.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recharge.create_time
     *
     * @param createTime the value for t_recharge.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}