package com.example.demo.pojo;

import java.util.Date;

public class TRepaymentDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_detail.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_detail.bid_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String bidId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_detail.borrow_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String borrowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_detail.repayment_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String repaymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_detail.borrow_user_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String borrowUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_detail.bid_user_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String bidUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_detail.borrow_title
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String borrowTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_detail.total_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Long totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_detail.principal
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Long principal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_detail.interest
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Long interest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_detail.period
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Integer period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_detail.deadline
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Date deadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_detail.repayment_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Date repaymentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_detail.repayment_type
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Integer repaymentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment_detail.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_detail.id
     *
     * @return the value of t_repayment_detail.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_detail.id
     *
     * @param id the value for t_repayment_detail.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_detail.bid_id
     *
     * @return the value of t_repayment_detail.bid_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getBidId() {
        return bidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_detail.bid_id
     *
     * @param bidId the value for t_repayment_detail.bid_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setBidId(String bidId) {
        this.bidId = bidId == null ? null : bidId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_detail.borrow_id
     *
     * @return the value of t_repayment_detail.borrow_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getBorrowId() {
        return borrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_detail.borrow_id
     *
     * @param borrowId the value for t_repayment_detail.borrow_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setBorrowId(String borrowId) {
        this.borrowId = borrowId == null ? null : borrowId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_detail.repayment_id
     *
     * @return the value of t_repayment_detail.repayment_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getRepaymentId() {
        return repaymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_detail.repayment_id
     *
     * @param repaymentId the value for t_repayment_detail.repayment_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setRepaymentId(String repaymentId) {
        this.repaymentId = repaymentId == null ? null : repaymentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_detail.borrow_user_id
     *
     * @return the value of t_repayment_detail.borrow_user_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getBorrowUserId() {
        return borrowUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_detail.borrow_user_id
     *
     * @param borrowUserId the value for t_repayment_detail.borrow_user_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setBorrowUserId(String borrowUserId) {
        this.borrowUserId = borrowUserId == null ? null : borrowUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_detail.bid_user_id
     *
     * @return the value of t_repayment_detail.bid_user_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getBidUserId() {
        return bidUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_detail.bid_user_id
     *
     * @param bidUserId the value for t_repayment_detail.bid_user_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setBidUserId(String bidUserId) {
        this.bidUserId = bidUserId == null ? null : bidUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_detail.borrow_title
     *
     * @return the value of t_repayment_detail.borrow_title
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getBorrowTitle() {
        return borrowTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_detail.borrow_title
     *
     * @param borrowTitle the value for t_repayment_detail.borrow_title
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setBorrowTitle(String borrowTitle) {
        this.borrowTitle = borrowTitle == null ? null : borrowTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_detail.total_amount
     *
     * @return the value of t_repayment_detail.total_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Long getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_detail.total_amount
     *
     * @param totalAmount the value for t_repayment_detail.total_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setTotalAmount(Long totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_detail.principal
     *
     * @return the value of t_repayment_detail.principal
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Long getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_detail.principal
     *
     * @param principal the value for t_repayment_detail.principal
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setPrincipal(Long principal) {
        this.principal = principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_detail.interest
     *
     * @return the value of t_repayment_detail.interest
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Long getInterest() {
        return interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_detail.interest
     *
     * @param interest the value for t_repayment_detail.interest
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setInterest(Long interest) {
        this.interest = interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_detail.period
     *
     * @return the value of t_repayment_detail.period
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Integer getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_detail.period
     *
     * @param period the value for t_repayment_detail.period
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setPeriod(Integer period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_detail.deadline
     *
     * @return the value of t_repayment_detail.deadline
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_detail.deadline
     *
     * @param deadline the value for t_repayment_detail.deadline
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_detail.repayment_time
     *
     * @return the value of t_repayment_detail.repayment_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Date getRepaymentTime() {
        return repaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_detail.repayment_time
     *
     * @param repaymentTime the value for t_repayment_detail.repayment_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setRepaymentTime(Date repaymentTime) {
        this.repaymentTime = repaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_detail.repayment_type
     *
     * @return the value of t_repayment_detail.repayment_type
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Integer getRepaymentType() {
        return repaymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_detail.repayment_type
     *
     * @param repaymentType the value for t_repayment_detail.repayment_type
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setRepaymentType(Integer repaymentType) {
        this.repaymentType = repaymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment_detail.create_time
     *
     * @return the value of t_repayment_detail.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment_detail.create_time
     *
     * @param createTime the value for t_repayment_detail.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}