package com.example.demo.pojo;

import java.util.Date;

public class TRepayment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment.borrow_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String borrowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment.borrow_user_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String borrowUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment.borrow_title
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String borrowTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment.deadline
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Date deadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment.repayment_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Date repaymentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment.total_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Long totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment.principal
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Long principal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment.interest
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Long interest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment.period
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Integer period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment.state
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment.borrow_type
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Integer borrowType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment.repayment_type
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Integer repaymentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_repayment.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment.id
     *
     * @return the value of t_repayment.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment.id
     *
     * @param id the value for t_repayment.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment.borrow_id
     *
     * @return the value of t_repayment.borrow_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getBorrowId() {
        return borrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment.borrow_id
     *
     * @param borrowId the value for t_repayment.borrow_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setBorrowId(String borrowId) {
        this.borrowId = borrowId == null ? null : borrowId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment.borrow_user_id
     *
     * @return the value of t_repayment.borrow_user_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getBorrowUserId() {
        return borrowUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment.borrow_user_id
     *
     * @param borrowUserId the value for t_repayment.borrow_user_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setBorrowUserId(String borrowUserId) {
        this.borrowUserId = borrowUserId == null ? null : borrowUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment.borrow_title
     *
     * @return the value of t_repayment.borrow_title
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getBorrowTitle() {
        return borrowTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment.borrow_title
     *
     * @param borrowTitle the value for t_repayment.borrow_title
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setBorrowTitle(String borrowTitle) {
        this.borrowTitle = borrowTitle == null ? null : borrowTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment.deadline
     *
     * @return the value of t_repayment.deadline
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment.deadline
     *
     * @param deadline the value for t_repayment.deadline
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment.repayment_time
     *
     * @return the value of t_repayment.repayment_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Date getRepaymentTime() {
        return repaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment.repayment_time
     *
     * @param repaymentTime the value for t_repayment.repayment_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setRepaymentTime(Date repaymentTime) {
        this.repaymentTime = repaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment.total_amount
     *
     * @return the value of t_repayment.total_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Long getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment.total_amount
     *
     * @param totalAmount the value for t_repayment.total_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setTotalAmount(Long totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment.principal
     *
     * @return the value of t_repayment.principal
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Long getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment.principal
     *
     * @param principal the value for t_repayment.principal
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setPrincipal(Long principal) {
        this.principal = principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment.interest
     *
     * @return the value of t_repayment.interest
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Long getInterest() {
        return interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment.interest
     *
     * @param interest the value for t_repayment.interest
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setInterest(Long interest) {
        this.interest = interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment.period
     *
     * @return the value of t_repayment.period
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Integer getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment.period
     *
     * @param period the value for t_repayment.period
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setPeriod(Integer period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment.state
     *
     * @return the value of t_repayment.state
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment.state
     *
     * @param state the value for t_repayment.state
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment.borrow_type
     *
     * @return the value of t_repayment.borrow_type
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Integer getBorrowType() {
        return borrowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment.borrow_type
     *
     * @param borrowType the value for t_repayment.borrow_type
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setBorrowType(Integer borrowType) {
        this.borrowType = borrowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment.repayment_type
     *
     * @return the value of t_repayment.repayment_type
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Integer getRepaymentType() {
        return repaymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment.repayment_type
     *
     * @param repaymentType the value for t_repayment.repayment_type
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setRepaymentType(Integer repaymentType) {
        this.repaymentType = repaymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repayment.create_time
     *
     * @return the value of t_repayment.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repayment.create_time
     *
     * @param createTime the value for t_repayment.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}