package com.example.demo.pojo;

import java.util.Date;

public class TSystemDictionaryItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_dictionary_item.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_dictionary_item.parent_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_dictionary_item.value
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_dictionary_item.order_no
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Integer orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_dictionary_item.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_dictionary_item.id
     *
     * @return the value of t_system_dictionary_item.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_dictionary_item.id
     *
     * @param id the value for t_system_dictionary_item.id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_dictionary_item.parent_id
     *
     * @return the value of t_system_dictionary_item.parent_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_dictionary_item.parent_id
     *
     * @param parentId the value for t_system_dictionary_item.parent_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_dictionary_item.value
     *
     * @return the value of t_system_dictionary_item.value
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_dictionary_item.value
     *
     * @param value the value for t_system_dictionary_item.value
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_dictionary_item.order_no
     *
     * @return the value of t_system_dictionary_item.order_no
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_dictionary_item.order_no
     *
     * @param orderNo the value for t_system_dictionary_item.order_no
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_dictionary_item.create_time
     *
     * @return the value of t_system_dictionary_item.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_dictionary_item.create_time
     *
     * @param createTime the value for t_system_dictionary_item.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}