package com.example.demo.pojo;

import java.util.Date;

public class TUserWallet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_wallet.account_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_wallet.available_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Long availableAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_wallet.freeze_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Long freezeAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_wallet.interest_pending
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Long interestPending;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_wallet.principal_pending
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Long principalPending;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_wallet.repaid_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Long repaidAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_wallet.credit_score
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Integer creditScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_wallet.credit_line
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Long creditLine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_wallet.residual_credit_line
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Long residualCreditLine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_wallet.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_wallet.account_id
     *
     * @return the value of t_user_wallet.account_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_wallet.account_id
     *
     * @param accountId the value for t_user_wallet.account_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_wallet.available_amount
     *
     * @return the value of t_user_wallet.available_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Long getAvailableAmount() {
        return availableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_wallet.available_amount
     *
     * @param availableAmount the value for t_user_wallet.available_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setAvailableAmount(Long availableAmount) {
        this.availableAmount = availableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_wallet.freeze_amount
     *
     * @return the value of t_user_wallet.freeze_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Long getFreezeAmount() {
        return freezeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_wallet.freeze_amount
     *
     * @param freezeAmount the value for t_user_wallet.freeze_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setFreezeAmount(Long freezeAmount) {
        this.freezeAmount = freezeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_wallet.interest_pending
     *
     * @return the value of t_user_wallet.interest_pending
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Long getInterestPending() {
        return interestPending;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_wallet.interest_pending
     *
     * @param interestPending the value for t_user_wallet.interest_pending
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setInterestPending(Long interestPending) {
        this.interestPending = interestPending;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_wallet.principal_pending
     *
     * @return the value of t_user_wallet.principal_pending
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Long getPrincipalPending() {
        return principalPending;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_wallet.principal_pending
     *
     * @param principalPending the value for t_user_wallet.principal_pending
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setPrincipalPending(Long principalPending) {
        this.principalPending = principalPending;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_wallet.repaid_amount
     *
     * @return the value of t_user_wallet.repaid_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Long getRepaidAmount() {
        return repaidAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_wallet.repaid_amount
     *
     * @param repaidAmount the value for t_user_wallet.repaid_amount
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setRepaidAmount(Long repaidAmount) {
        this.repaidAmount = repaidAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_wallet.credit_score
     *
     * @return the value of t_user_wallet.credit_score
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Integer getCreditScore() {
        return creditScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_wallet.credit_score
     *
     * @param creditScore the value for t_user_wallet.credit_score
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setCreditScore(Integer creditScore) {
        this.creditScore = creditScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_wallet.credit_line
     *
     * @return the value of t_user_wallet.credit_line
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Long getCreditLine() {
        return creditLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_wallet.credit_line
     *
     * @param creditLine the value for t_user_wallet.credit_line
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setCreditLine(Long creditLine) {
        this.creditLine = creditLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_wallet.residual_credit_line
     *
     * @return the value of t_user_wallet.residual_credit_line
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Long getResidualCreditLine() {
        return residualCreditLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_wallet.residual_credit_line
     *
     * @param residualCreditLine the value for t_user_wallet.residual_credit_line
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setResidualCreditLine(Long residualCreditLine) {
        this.residualCreditLine = residualCreditLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_wallet.create_time
     *
     * @return the value of t_user_wallet.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_wallet.create_time
     *
     * @param createTime the value for t_user_wallet.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}