package com.example.demo.pojo;

import java.util.Date;

public class TUserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.account_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.avatar
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.realname
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.id_card_number
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String idCardNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.phone_number
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.income_level_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Integer incomeLevelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.marriage_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Integer marriageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.edu_background_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Integer eduBackgroundId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.house_condition_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Integer houseConditionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.account_id
     *
     * @return the value of t_user_info.account_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.account_id
     *
     * @param accountId the value for t_user_info.account_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.avatar
     *
     * @return the value of t_user_info.avatar
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.avatar
     *
     * @param avatar the value for t_user_info.avatar
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.realname
     *
     * @return the value of t_user_info.realname
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.realname
     *
     * @param realname the value for t_user_info.realname
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.id_card_number
     *
     * @return the value of t_user_info.id_card_number
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getIdCardNumber() {
        return idCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.id_card_number
     *
     * @param idCardNumber the value for t_user_info.id_card_number
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setIdCardNumber(String idCardNumber) {
        this.idCardNumber = idCardNumber == null ? null : idCardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.phone_number
     *
     * @return the value of t_user_info.phone_number
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.phone_number
     *
     * @param phoneNumber the value for t_user_info.phone_number
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.income_level_id
     *
     * @return the value of t_user_info.income_level_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Integer getIncomeLevelId() {
        return incomeLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.income_level_id
     *
     * @param incomeLevelId the value for t_user_info.income_level_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setIncomeLevelId(Integer incomeLevelId) {
        this.incomeLevelId = incomeLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.marriage_id
     *
     * @return the value of t_user_info.marriage_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Integer getMarriageId() {
        return marriageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.marriage_id
     *
     * @param marriageId the value for t_user_info.marriage_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setMarriageId(Integer marriageId) {
        this.marriageId = marriageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.edu_background_id
     *
     * @return the value of t_user_info.edu_background_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Integer getEduBackgroundId() {
        return eduBackgroundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.edu_background_id
     *
     * @param eduBackgroundId the value for t_user_info.edu_background_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setEduBackgroundId(Integer eduBackgroundId) {
        this.eduBackgroundId = eduBackgroundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.house_condition_id
     *
     * @return the value of t_user_info.house_condition_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Integer getHouseConditionId() {
        return houseConditionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.house_condition_id
     *
     * @param houseConditionId the value for t_user_info.house_condition_id
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setHouseConditionId(Integer houseConditionId) {
        this.houseConditionId = houseConditionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.create_time
     *
     * @return the value of t_user_info.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.create_time
     *
     * @param createTime the value for t_user_info.create_time
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}