package com.example.demo.dao;

import com.example.demo.pojo.TAccountFlow;
import com.example.demo.pojo.TWithdraw;
import org.apache.ibatis.annotations.Param;

public interface TAccountFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_flow
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_flow
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int insert(TAccountFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_flow
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int insertSelective(TAccountFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_flow
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    TAccountFlow selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_flow
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int updateByPrimaryKeySelective(TAccountFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_flow
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int updateByPrimaryKey(TAccountFlow record);

    /**
     * 根据id查询流水账
     * @param userId
     * @return
     */
    TAccountFlow query(@Param("userid") String userId);

}