package com.example.demo.dao;

import com.example.demo.pojo.TBankCard;
import org.apache.ibatis.annotations.Param;

public interface TBankCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bank_card
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bank_card
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int insert(TBankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bank_card
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int insertSelective(TBankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bank_card
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    TBankCard selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bank_card
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int updateByPrimaryKeySelective(TBankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bank_card
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int updateByPrimaryKey(TBankCard record);

    TBankCard getBackCarUserId(@Param("userid") String userId);

    int updateWithdrawMoney(TBankCard tBankCard);
}