package com.example.demo.dao;

import com.example.demo.pojo.TBorrow;
import org.apache.ibatis.annotations.Param;

public interface TBorrowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int insert(TBorrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int insertSelective(TBorrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    TBorrow selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int updateByPrimaryKeySelective(TBorrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int updateByPrimaryKey(TBorrow record);

    TBorrow select(String id);

    int update(TBorrow borrow);

    TBorrow getBorrowId(@Param("borrowId") String borrowId);

}