package com.example.demo.dao;

import com.example.demo.pojo.RechergeCondition;
import com.example.demo.pojo.TRecharge;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TRechargeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int insert(TRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int  insertSelective(TRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    TRecharge selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int updateByPrimaryKeySelective(TRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recharge
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int updateByPrimaryKey(TRecharge record);

    /**
     * 按条件查询
     * @param rechergeCondition
     * @return
     */
    List<TRecharge> query(RechergeCondition rechergeCondition);


    Integer rechargeCount(RechergeCondition rechergeCondition);
}