package com.example.demo.dao;

import com.example.demo.pojo.RepaCondition;
import com.example.demo.pojo.TRepayment;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TRepaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repayment
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repayment
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int insert(TRepayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repayment
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int insertSelective(TRepayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repayment
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    TRepayment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repayment
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int updateByPrimaryKeySelective(TRepayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repayment
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int updateByPrimaryKey(TRepayment record);


    Integer count(@Param("repa") RepaCondition repaCondition);

    List<TRepayment> query(@Param("repa") RepaCondition repaCondition);

    TRepayment getRepayInfo(@Param("id")String id,@Param("borUserId")String userId);
}