package com.example.demo.dao;

import com.example.demo.pojo.TRepayment;
import com.example.demo.pojo.TRepaymentDetail;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TRepaymentDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repayment_detail
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repayment_detail
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int insert(TRepaymentDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repayment_detail
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int insertSelective(TRepaymentDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repayment_detail
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    TRepaymentDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repayment_detail
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int updateByPrimaryKeySelective(TRepaymentDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_repayment_detail
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int updateByPrimaryKey(TRepaymentDetail record);

    List<TRepayment> getBorrowId(@Param("borrowId") String borrowId);
}