package com.example.demo.dao;

import com.example.demo.pojo.Page;
import com.example.demo.pojo.TSystemDictionary;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TSystemDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_dictionary
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_dictionary
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int insert(TSystemDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_dictionary
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int insertSelective(TSystemDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_dictionary
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    TSystemDictionary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_dictionary
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int updateByPrimaryKeySelective(TSystemDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_dictionary
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int updateByPrimaryKey(TSystemDictionary record);

    /**
     * 根据关键字、页码查询
     * @param name
     * @param page
     * @return
     */
    List<TSystemDictionary> getQuery(@Param("keyword") String name, @Param("page") Page page);

    /**
     * 根据条件查询数量
     * @return
     */
    Integer getQueryCount(@Param("keyword") String name,Page page);


    List<TSystemDictionary> getAll();
}