package com.example.demo.dao;

import com.example.demo.pojo.RegisterUser;
import com.example.demo.pojo.TUserAccount;
import com.example.demo.pojo.TUserInfo;
import org.apache.ibatis.annotations.Param;

public interface TUserAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int insert(TUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int insertSelective(TUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    TUserAccount selectByPrimaryKey(String id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int updateByPrimaryKeySelective(TUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account
     *
     * @mbg.generated Fri Oct 11 11:28:27 CST 2019
     */
    int updateByPrimaryKey(TUserAccount record);

    /**
     * 验证用户名
     * @param userName
     * @return
     */
    TUserAccount selectUserAccountUserName(@Param("userName") String userName);

    TUserInfo seleAll(@Param("userId") String userId);





}